// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBP_API.Entities;

#nullable disable

namespace NBP_API.Migrations
{
    [DbContext(typeof(ExchangeRatesDbContext))]
    [Migration("20220828222757_Table_Rate2_Added")]
    partial class Table_Rate2_Added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NBP_API.Entities.ExchangeRates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EffectiveDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradingDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("NBP_API.Entities.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExchangeRatesId")
                        .HasColumnType("int");

                    b.Property<string>("Mid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeRatesId");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("NBP_API.Entities.Rate2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AUD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BGN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CZK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DKK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EUR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExchangeRatesId")
                        .HasColumnType("int");

                    b.Property<string>("GBP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HKD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HUF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JPY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KRW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MXN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MYR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NZD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeRatesId");

                    b.ToTable("Rates2");
                });

            modelBuilder.Entity("NBP_API.Entities.Rate", b =>
                {
                    b.HasOne("NBP_API.Entities.ExchangeRates", "ExchangeRates")
                        .WithMany("rates")
                        .HasForeignKey("ExchangeRatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeRates");
                });

            modelBuilder.Entity("NBP_API.Entities.Rate2", b =>
                {
                    b.HasOne("NBP_API.Entities.ExchangeRates", "ExchangeRates")
                        .WithMany("rates2")
                        .HasForeignKey("ExchangeRatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeRates");
                });

            modelBuilder.Entity("NBP_API.Entities.ExchangeRates", b =>
                {
                    b.Navigation("rates");

                    b.Navigation("rates2");
                });
#pragma warning restore 612, 618
        }
    }
}
